= Nordic44 Model - Description
:author: Svein Olsen
:revnumber: 3.0.0.alpha.1
:revdate: {docdate}


== Introduction

This file is accommodating the machine-readably link:manifest.xml['manifest'] and provide a human readable text that describe the content of the underlying folders.
The Nordic44 is a synthetic power system model of the Nordic high-voltage transmission system described and compliant with the Common Grid Model Exchange Standard (CGMES). 

- `cimxml/` – Contains CIM XML files (a dialogues based on RDF XML) according to *IEC 61970-600-1* (that based on and provide some discrepancy to IEC 61970-552:2016). These file would be used for CGMES supporeted power flow tools. 
- `jsonld/` – Contains CIM JSON-LD plan to be addressed in *IEC 61970-553* that will be a serialization format, *fully compatible with Semantic Web standards*..
- `trig/` – Contains link:https://www.w3.org/TR/trig/[TriG format] version of the model addressing a more hyuman readable format that will be used for human documentation. 

Currently is the file in link:cimxml[cimxml folder] the master and will be translated into link:https://www.w3.org/TR/json-ld11/[JSON-LD] and located in link:jsonld[jsonld folder] and into link:https://www.w3.org/TR/trig/[TriG] and located in link:trig[trig folder]

== Validation Approach

The files will be validated against CGMES 3.0 and Network Code Profile (NCP) profiles described in SHACL. The CIM XML file will be tested for power flow in a CGMES supported power flow tool. 

== Changelog

Nordic44 follows *Semantic Versioning 2.0.0 (link:https://semver.org/[SemVer])* with support for **pre-release versions**:  
`{Major}.{Minor}.{Patch}-{PreRelease}.{Iteration}`  

- **Major (`X.0.0`)** – Significant, non-backwards-compatible changes. E.g. transition to a new version of CGMES.
- **Minor (`X.Y.0`)** – Backwards-compatible improvements. E.g. adding significant set of object that is compatible with the profile. The dataset should conform to the same profile. Adding a new dataset shall require minor version upgrade.
- **Patch (`X.Y.Z`)** – Minor fixes or adjustment with no impact on structure. E.g. adding attribute to existing object or create new object of type that already exist in the dataset.
- **Pre-release (`alpha`, `beta`)** – Versions that may undergo further revisions prior to final release.
- **Iteration (`X`)** – Incremental release number within `alpha` or `beta`.  Sequential number for the pre-release phase.

=== Examples:

- 3.0.0-alpha.1 – First alpha version (early-stage, subject to major revisions).
- 3.0.0-beta.3 – Third beta release (more stable, but could still change).
- 3.0.0 – Finalised version.


[cols="3,2,5,2",options="header"]
|===
| Version | Date | Description | Issue
| 3.0.0-beta.1 | 2025-02-14 | Update Manifest with the header information that will be used in NCP | link:https://github.com/statnett/Nordic44/issues/15[#15]
| 3.0.0-alpha.1 | 2025-02-12 | Remove entsoe and entsoe2 namespaces  | link:https://github.com/statnett/Nordic44/issues/10[#10]
| 3.0.0-alpha.1 | 2025-02-12 | Converting Nordic version 38 to CGMES 3.0  | link:https://github.com/statnett/Nordic44/issues/9[#9]
|===

For further details, refer to the changelog history on GitHub:  
🔗 https://github.com/statnett/Nordic44/issues

